baseURL = "https://playtaiwanese.tw/"
DefaultContentLanguage = "zh-hant" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-tw"
title = "玩轉攻臺藝"
copyright = "玩轉攻臺藝 2023"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "語你同在一起"
enableAutoDarkMode=true
favicon = "/images/icon.png"
walineServer = "https://ptc-omment.vercel.app"
enableReadingTime=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "文章"
weight = 1
[[menu.main]]
url = "/categories"
name = "分類"
weight = 2
[[menu.main]]
url = "/tags"
name = "標籤"
weight = 3

[[menu.main]]
url = "/about"
name = "關於我們"
weight = 4
